### ISSUE TITLE
unzip (without progress) promise completed before zip file actually extracted

### ISSUE THREAD

**Issue by SBD580** [triniwiz/nativescript-zip#8]
The promise returned from `unzip` is just wrong. The promise should resolved when the extraction is over (else there is no need for a promise at all).

**Comment by ddfreiling** [comment]
I assume you mean on Android, due to this line:
https://github.com/triniwiz/nativescript-zip/blob/master/zip.android.ts#L55

I'd suggest just using `unzipWithProgress` with an empty progress callback if you don't need it. Honestly the old unzip should just be removed and the progress callback be made optional. I think both were kept to avoid breaking changes.

**Comment by triniwiz** [comment]
Fixed in v2
